// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: github/ayonli/ngrpc/services/PostService.proto

package services_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PostQuery) Reset() {
	*x = PostQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_ayonli_ngrpc_services_PostService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostQuery) ProtoMessage() {}

func (x *PostQuery) ProtoReflect() protoreflect.Message {
	mi := &file_github_ayonli_ngrpc_services_PostService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostQuery.ProtoReflect.Descriptor instead.
func (*PostQuery) Descriptor() ([]byte, []int) {
	return file_github_ayonli_ngrpc_services_PostService_proto_rawDescGZIP(), []int{0}
}

func (x *PostQuery) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PostsQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Author  *string `protobuf:"bytes,1,opt,name=author,proto3,oneof" json:"author,omitempty"`
	Keyword *string `protobuf:"bytes,2,opt,name=keyword,proto3,oneof" json:"keyword,omitempty"`
}

func (x *PostsQuery) Reset() {
	*x = PostsQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_ayonli_ngrpc_services_PostService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostsQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostsQuery) ProtoMessage() {}

func (x *PostsQuery) ProtoReflect() protoreflect.Message {
	mi := &file_github_ayonli_ngrpc_services_PostService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostsQuery.ProtoReflect.Descriptor instead.
func (*PostsQuery) Descriptor() ([]byte, []int) {
	return file_github_ayonli_ngrpc_services_PostService_proto_rawDescGZIP(), []int{1}
}

func (x *PostsQuery) GetAuthor() string {
	if x != nil && x.Author != nil {
		return *x.Author
	}
	return ""
}

func (x *PostsQuery) GetKeyword() string {
	if x != nil && x.Keyword != nil {
		return *x.Keyword
	}
	return ""
}

type PostSearchResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Posts []*Post `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
}

func (x *PostSearchResult) Reset() {
	*x = PostSearchResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_ayonli_ngrpc_services_PostService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostSearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostSearchResult) ProtoMessage() {}

func (x *PostSearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_github_ayonli_ngrpc_services_PostService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostSearchResult.ProtoReflect.Descriptor instead.
func (*PostSearchResult) Descriptor() ([]byte, []int) {
	return file_github_ayonli_ngrpc_services_PostService_proto_rawDescGZIP(), []int{2}
}

func (x *PostSearchResult) GetPosts() []*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

var File_github_ayonli_ngrpc_services_PostService_proto protoreflect.FileDescriptor

var file_github_ayonli_ngrpc_services_PostService_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2f, 0x61, 0x79, 0x6f, 0x6e, 0x6c, 0x69, 0x2f,
	0x6e, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x50,
	0x6f, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x1c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x61, 0x79, 0x6f, 0x6e, 0x6c, 0x69, 0x2e,
	0x6e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x1a, 0x29,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2f, 0x61, 0x79, 0x6f, 0x6e, 0x6c, 0x69, 0x2f, 0x6e, 0x67,
	0x72, 0x70, 0x63, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x73, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1b, 0x0a, 0x09, 0x50, 0x6f, 0x73,
	0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x5f, 0x0a, 0x0a, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x12, 0x1b, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x88, 0x01,
	0x01, 0x12, 0x1d, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x01, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x88, 0x01, 0x01,
	0x42, 0x09, 0x0a, 0x07, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x42, 0x0a, 0x0a, 0x08, 0x5f,
	0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x4c, 0x0a, 0x10, 0x50, 0x6f, 0x73, 0x74, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x38, 0x0a, 0x05, 0x70,
	0x6f, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x61, 0x79, 0x6f, 0x6e, 0x6c, 0x69, 0x2e, 0x6e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x05,
	0x70, 0x6f, 0x73, 0x74, 0x73, 0x32, 0xd2, 0x01, 0x0a, 0x0b, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x58, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x74,
	0x12, 0x27, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x61, 0x79, 0x6f, 0x6e, 0x6c, 0x69,
	0x2e, 0x6e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e,
	0x50, 0x6f, 0x73, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x1a, 0x22, 0x2e, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x61, 0x79, 0x6f, 0x6e, 0x6c, 0x69, 0x2e, 0x6e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x22, 0x00, 0x12,
	0x69, 0x0a, 0x0b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x12, 0x28,
	0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x61, 0x79, 0x6f, 0x6e, 0x6c, 0x69, 0x2e, 0x6e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x50, 0x6f,
	0x73, 0x74, 0x73, 0x51, 0x75, 0x65, 0x72, 0x79, 0x1a, 0x2e, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x61, 0x79, 0x6f, 0x6e, 0x6c, 0x69, 0x2e, 0x6e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2f, 0x61, 0x79, 0x6f, 0x6e, 0x6c, 0x69, 0x2f, 0x6e, 0x67, 0x72, 0x70,
	0x63, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_ayonli_ngrpc_services_PostService_proto_rawDescOnce sync.Once
	file_github_ayonli_ngrpc_services_PostService_proto_rawDescData = file_github_ayonli_ngrpc_services_PostService_proto_rawDesc
)

func file_github_ayonli_ngrpc_services_PostService_proto_rawDescGZIP() []byte {
	file_github_ayonli_ngrpc_services_PostService_proto_rawDescOnce.Do(func() {
		file_github_ayonli_ngrpc_services_PostService_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_ayonli_ngrpc_services_PostService_proto_rawDescData)
	})
	return file_github_ayonli_ngrpc_services_PostService_proto_rawDescData
}

var file_github_ayonli_ngrpc_services_PostService_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_github_ayonli_ngrpc_services_PostService_proto_goTypes = []interface{}{
	(*PostQuery)(nil),        // 0: github.ayonli.ngrpc.services.PostQuery
	(*PostsQuery)(nil),       // 1: github.ayonli.ngrpc.services.PostsQuery
	(*PostSearchResult)(nil), // 2: github.ayonli.ngrpc.services.PostSearchResult
	(*Post)(nil),             // 3: github.ayonli.ngrpc.services.Post
}
var file_github_ayonli_ngrpc_services_PostService_proto_depIdxs = []int32{
	3, // 0: github.ayonli.ngrpc.services.PostSearchResult.posts:type_name -> github.ayonli.ngrpc.services.Post
	0, // 1: github.ayonli.ngrpc.services.PostService.GetPost:input_type -> github.ayonli.ngrpc.services.PostQuery
	1, // 2: github.ayonli.ngrpc.services.PostService.SearchPosts:input_type -> github.ayonli.ngrpc.services.PostsQuery
	3, // 3: github.ayonli.ngrpc.services.PostService.GetPost:output_type -> github.ayonli.ngrpc.services.Post
	2, // 4: github.ayonli.ngrpc.services.PostService.SearchPosts:output_type -> github.ayonli.ngrpc.services.PostSearchResult
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_github_ayonli_ngrpc_services_PostService_proto_init() }
func file_github_ayonli_ngrpc_services_PostService_proto_init() {
	if File_github_ayonli_ngrpc_services_PostService_proto != nil {
		return
	}
	file_github_ayonli_ngrpc_services_struct_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_github_ayonli_ngrpc_services_PostService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_ayonli_ngrpc_services_PostService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostsQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_ayonli_ngrpc_services_PostService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostSearchResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_github_ayonli_ngrpc_services_PostService_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_ayonli_ngrpc_services_PostService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_ayonli_ngrpc_services_PostService_proto_goTypes,
		DependencyIndexes: file_github_ayonli_ngrpc_services_PostService_proto_depIdxs,
		MessageInfos:      file_github_ayonli_ngrpc_services_PostService_proto_msgTypes,
	}.Build()
	File_github_ayonli_ngrpc_services_PostService_proto = out.File
	file_github_ayonli_ngrpc_services_PostService_proto_rawDesc = nil
	file_github_ayonli_ngrpc_services_PostService_proto_goTypes = nil
	file_github_ayonli_ngrpc_services_PostService_proto_depIdxs = nil
}
