name: Node and Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - run: npm i
    - run: npx tsc
    - run: go mod tidy
    - run: go install github.com/ayonli/ngrpc/cli/ngrpc

    - name: Test Node.js
      run: npm test
    - name: Test Go:util
      run: go test -v --timeout 60s ./util
    - name: Test Go:config
      run: go test -v --timeout 60s ./config
    - name: Test Go:pm
      run: go test -v --timeout 60s ./pm
    - name: Test Go
      run: go test --timeout 60s -v .
