# This workflow will test a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - run: go install github.com/ayonli/ngrpc/cli/ngrpc

    - name: Test config
      run: go test -v --timeout 60s ./config
    - name: Test host
      run: go test -v --timeout 60s ./host
    - name: Test util
      run: go test -v --timeout 60s ./util
    - name: Test main
      run: go test --timeout 60s -v .

